/**
 * Academic AI Engine
 * Provides intelligent mapping and generation for grading, lesson planning, and academic advice.
 */

export interface GradeInfo {
    grade: string;
    comment: string;
    tip: string;
    color: string;
}

export const getGradeInfo = (score: number): GradeInfo => {
    if (score >= 90) return {
        grade: "A+",
        comment: "Exceptional mastery of the subject. Demonstrates deep understanding and critical thinking.",
        tip: "You're ready for advanced topics! Try exploring some university-level resources in this subject.",
        color: "text-green-600"
    };
    if (score >= 80) return {
        grade: "A",
        comment: "Strong performance. Well above average understanding of the curriculum.",
        tip: "Focus on refining your practical applications and solving complex problem sets.",
        color: "text-green-500"
    };
    if (score >= 70) return {
        grade: "B",
        comment: "Good work. Solid grasp of most concepts with some room for finer detail.",
        tip: "Review the chapters you found most challenging and try to explain them to a peer.",
        color: "text-blue-500"
    };
    if (score >= 60) return {
        grade: "C",
        comment: "Fair performance. Meets basic requirements but needs more consistency.",
        tip: "Use active recall and spaced repetition to strengthen your memory of key facts.",
        color: "text-yellow-600"
    };
    if (score >= 50) return {
        grade: "D",
        comment: "Below average. Demonstrates partial understanding of the subject matter.",
        tip: "Dedicate more time to daily review and don't hesitate to ask your teacher for help.",
        color: "text-orange-600"
    };
    return {
        grade: "F",
        comment: "Unsatisfactory. Significant gaps in knowledge and application.",
        tip: "Focus on the absolute fundamentals first. Consistent, small daily study sessions are key to catching up.",
        color: "text-red-600"
    };
};

export const generateLessonPlan = (subject: string, level: string, topic: string, duration: string) => {
    return `
# Lesson Plan: ${topic}
**Subject:** ${subject} | **Level:** ${level} | **Duration:** ${duration}

## Learning Objectives
By the end of this lesson, students will be able to:
1. Define the core concepts of ${topic}.
2. Explain the practical importance of ${topic} in real-world scenarios.
3. Demonstrate a basic level of proficiency in solving problems related to this topic.

## Required Materials
- Textbook: Standard ${subject} for ${level}
- Whiteboard and colored markers
- Prepared handouts with summary notes
- [AI Suggestion]: Interactive digital charts or multimedia presentation if available

## Lesson Structure

### 1. Introduction (5-10 mins)
- Hook: Start with a real-life example of how ${topic} affects our daily lives.
- Bridging: Briefly connect today's topic to previous lessons in ${subject}.
- State the specific learning objectives for today.

### 2. Core Instruction (20-30 mins)
- Define key terminology related to ${topic}.
- Step-by-step walkthrough of the main theories or processes.
- Use visual aids to illustrate complex points.
- Check for understanding every 10 minutes with quick questions.

### 3. Practical Activity (15-20 mins)
- Divide students into small groups.
- Task: Solve a series of progressive problems or analyze a case study on ${topic}.
- Teacher circulates to provide guidance and answer questions.

### 4. Conclusion & Assessment (5-10 mins)
- Recap the three main takeaways from the lesson.
- Quick exit ticket: Students write one thing they learned and one question they still have.
- Assign relevant homework from the ${subject} workbook.

---
*Generated by Academic AI Assistant*
  `.trim();
};

export const getAcademicAdvice = (role: string, context?: any) => {
    if (role === "student") {
        const level = context?.level || "your level";
        const dept = context?.department || "";
        return [
            `As a ${level} ${dept} student, focus on consistent revision rather than cramming.`,
            `Mastering the foundational concepts in ${dept} now will make advanced topics much easier later.`,
            "Healthy sleep and nutrition are just as important as study time for memory retention.",
            "Try the Pomodoro technique: 25 minutes of deep focus followed by a 5-minute break."
        ];
    }
    if (role === "teacher") {
        return [
            "Incorporate more formative assessments to gauge student understanding in real-time.",
            "Differentiated instruction can help you reach students at varying levels of proficiency.",
            "Positive reinforcement often yields better results than strictly disciplinary measures.",
            "Encourage your students to ask 'Why' and 'How', not just 'What'."
        ];
    }
    if (role === "authority") {
        return [
            "Data-driven decisions based on term-over-term grade trends can improve school standards.",
            "Providing teachers with workshops on AI-assisted teaching can increase productivity.",
            "Monitoring student attendance and correlates with academic performance can identify at-risk students earlier.",
            "Regular feedback loops with parents and teachers ensure a unified school vision."
        ];
    }
    return ["Education is a journey, not a race. Stay curious!"];
};

/**
 * Processes a natural language query based on user role and context.
 */
export const processAIQuery = (query: string, role: string, context?: any): string => {
    const q = query.toLowerCase();

    // Interaction templates
    if (q.includes("hello") || q.includes("hi") || q.includes("hey")) {
        return `Hello! I am your Academic AI Assistant. How can I help you today as a ${role}?`;
    }

    if (q.includes("register") || q.includes("enroll")) {
        if (role === "authority") return "To register a user, go to the 'Register Users' section in your sidebar. Fill in their details, select their role, and the system will autogenerate their ID and password.";
        return "Registration is handled by the school authority. Please contact your principal for enrollment details.";
    }

    if (q.includes("grade") || q.includes("score") || q.includes("result")) {
        if (role === "teacher") return "You can submit grades in the 'Submit Grades' section. Use my 'AI Grade' button to get suggestions based on student scores!";
        if (role === "student") return "You can view your latest results in the 'My Grades' section of your dashboard.";
        return "The system allows teachers to submit grades which you can then review and approve in the 'Grades' section.";
    }

    if (q.includes("lesson") || q.includes("plan")) {
        if (role === "teacher") return "I have a dedicated 'AI Lesson Planner' section for you! Just enter the subject and topic, and I'll generate a full plan in seconds.";
        return "Teachers use my AI Lesson Planner to prepare structured lessons for students.";
    }

    if (q.includes("complaint") || q.includes("report issue")) {
        return "We have an AI-driven Complaint Assistant. You can find it in the sidebar to voice any concerns confidentially.";
    }

    if (q.includes("who are you") || q.includes("what do you do")) {
        return "I am a powerful Academic AI built into this system. I help with grading, lesson planning, performance analysis, and answering your administrative or academic questions.";
    }

    if (q.includes("thank")) {
        return "You're very welcome! Is there anything else I can assist you with?";
    }

    // Default intelligent fallbacks based on role
    if (role === "authority") return "That's an interesting question. From a school management perspective, I recommend looking at your 'Reports' section for data-driven insights, or 'Settings' to manage academic cycles.";
    if (role === "teacher") return "I suggest looking at your 'Materials' section to share resources, or using the 'AI Lesson Planner' to streamline your preparation for that topic.";

    return "I'm not exactly sure about that, but you can try asking about registration, grades, lesson plans, or school settings!";
};
